title: TSPARR Tech Thoughts
description: My thoughts on MacAdmin work and how it relates to infrastructure, automation, and DevOps
author: Tyler Sparr

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/tsparr" }

# Permalink structure
permalink: /:title/

# Exclude files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
