title: TSPARR Tech Thoughts
description: My thoughts on MacAdmin work and how it relates to infrastructure, automation, and DevOps
author:
  name: Tyler Sparr
  github: tsparr

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark

# Permalink structure
permalink: /:title/

# Exclude files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
